Repository besscroft/PicImpact, pull requests merged in 2025-03, with the labels that each got.

#230 chore: add dev command turbopack
  package.json
Labels: :wrench:chore

#231 chore: remove custom file upload
  components/admin/upload/FileUpload.tsx
Labels: :money_with_wings:wontfix

#234 refactor: add hono exception handler
  app/admin/settings/account/page.tsx
  components/admin/upload/FileUpload.tsx
  components/album/Masonry.tsx
  components/layout/DropMenu.tsx
  components/layout/VaulDrawer.tsx
  components/layout/admin/nav-user.tsx
  hono/albums.ts
  hono/auth.ts
  hono/copyrights.ts
  hono/file.ts
  hono/images.ts
  hono/index.ts
  hono/open/open.ts
  hono/settings.ts
  server/auth.ts
Labels: :recycle:refactor

#236 fix: fix animation for camera counter
  components/admin/dashboard/CardList.tsx
  components/animata/text/counter.tsx
Labels: :bug:bug

#238 refactor: update about page
  app/admin/about/page.tsx
  components/animata/card/evervault-card.tsx
  lib/github/get-contributors.ts
Labels: :recycle:refactor

#242 refactor: file upload module encapsulation
  hono/file.ts
  server/lib/file-upload.ts
  server/lib/s3api.ts
Labels: :recycle:refactor

#243 Refactor file upload
  components/admin/upload/FileUpload.tsx
  components/admin/upload/LivephotoFileUpload.tsx
  components/admin/upload/MultipleFileUpload.tsx
  components/admin/upload/SimpleFileUpload.tsx
  hono/file.ts
  lib/utils/file.ts
  package.json
  pnpm-lock.yaml
  server/lib/file-upload.ts
  types/index.ts
Labels: :recycle:refactor

#244 feat: add randomShow functionality to albums
  app/(default)/[...album]/page.tsx
  app/(default)/label/[...tag]/page.tsx
  app/(default)/page.tsx
  app/admin/settings/preferences/page.tsx
  components/admin/album/AlbumAddSheet.tsx
  components/admin/album/AlbumEditSheet.tsx
  components/album/Masonry.tsx
  hono/settings.ts
  instrumentation.ts
  messages/en.json
  messages/ja.json
  messages/zh-TW.json
  messages/zh.json
  prisma/migrations/20250316134415_add_random_show_for_album/migration.sql
  prisma/schema.prisma
  server/db/operate.ts
  server/db/query.ts
  types/index.ts
Labels: :sparkles:enhancement

#246 fix: mobile menu router collapsible error
  components/layout/admin/nav-main.tsx
  components/layout/admin/nav-projects.tsx
Labels: :bug:bug

#245 fix: route error when close the image detail page
  components/album/Masonry.tsx
  components/album/MasonryItem.tsx
Labels: :bug:bug

#248 fix: Upgrade Next.js package version
  package.json
  pnpm-lock.yaml
Labels: :wrench:chore

#252 feat: add bundle-analyzer
  next.config.mjs
  package.json
  pnpm-lock.yaml
Labels: :wrench:chore
