Repository besscroft/PicImpact, pull requests merged in 2025-02, with the labels that each got.

#203 v2.1.1
  Dockerfile
  app/(default)/[...album]/page.tsx
  app/admin/about/page.tsx
  components/admin/album/AlbumHelpSheet.tsx
  components/admin/album/AlbumList.tsx
  components/admin/list/ImageEditSheet.tsx
  components/layout/AlbumDrawer.tsx
  components/layout/DynamicNavbar.tsx
  components/layout/Header.tsx
  components/layout/HeaderLink.tsx
  components/layout/VaulDrawer.tsx
  components/ui/navigation-menu.tsx
  instrumentation.ts
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250201054843_v1_3/migration.sql
  prisma/schema.prisma
  server/db/operate.ts
  server/db/query.ts
  types/index.ts
Labels: :bug:bug, :sparkles:enhancement

#207 Fix issue 206
  app/admin/settings/preferences/page.tsx
  components/admin/album/AlbumHelpSheet.tsx
  components/admin/list/ImageEditSheet.tsx
  hono/settings.ts
  instrumentation.ts
  messages/en.json
  messages/ja.json
  messages/zh-TW.json
  messages/zh.json
  prisma/migrations/20250213051523_v1_4/migration.sql
  prisma/schema.prisma
  server/db/operate.ts
  server/db/query.ts
  types/index.ts
Labels: :bug:bug

#208 ci: 锁定 prisma 版本
  Dockerfile
  package.json
  pnpm-lock.yaml
  script.sh
Labels: :bug:bug

#210 v2.1.2
  Dockerfile
  app/admin/about/page.tsx
  app/admin/settings/preferences/page.tsx
  components/admin/album/AlbumHelpSheet.tsx
  components/admin/list/ImageEditSheet.tsx
  hono/settings.ts
  instrumentation.ts
  messages/en.json
  messages/ja.json
  messages/zh-TW.json
  messages/zh.json
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250213051523_v1_4/migration.sql
  prisma/schema.prisma
  script.sh
  server/db/operate.ts
  server/db/query.ts
  types/index.ts
Labels: :bug:bug

#211 fix: use more human friendly message for auth error
  components/login/UserFrom.tsx
  server/actions.ts
Labels: :sparkles:enhancement

#214 :bug: 修复精选模式下首页不显示复制和下载按钮问题。
  app/(default)/page.tsx
  app/admin/settings/preferences/page.tsx
  app/layout.tsx
  app/providers/config-store-Providers.tsx
  components/album/Masonry.tsx
  components/album/MasonryItem.tsx
  hono/settings.ts
  hooks/useSWRInfiniteHook.ts
  instrumentation.ts
  messages/en.json
  messages/ja.json
  messages/zh-TW.json
  messages/zh.json
  server/db/operate.ts
  stores/configStores.ts
  types/index.ts
Labels: :bug:bug

#215 v2.1.3
  app/admin/about/page.tsx
  messages/zh.json
  package.json
  pnpm-lock.yaml
Labels: :bug:bug

#216 :bug: 修复主题在某些情况下的识别问题
  app/providers/toaster-providers.tsx
  components/layout/DropMenu.tsx
  components/layout/VaulDrawer.tsx
  components/layout/admin/nav-user.tsx
  components/login/UserFrom.tsx
Labels: :bug:bug

#218 feat: Add btree index for exif field
  prisma/migrations/20250226144408_add_json_field_indexes/migration.sql
  prisma/schema.prisma
Labels: :sparkles:enhancement

#221 feat: Add album folding configuration options
  .gitignore
  app/admin/settings/preferences/page.tsx
  components/layout/Header.tsx
  components/layout/HeaderLink.tsx
  hono/settings.ts
  instrumentation.ts
  messages/en.json
  messages/ja.json
  messages/zh-TW.json
  messages/zh.json
  server/db/operate.ts
  server/db/query.ts
  types/index.ts
Labels: :sparkles:enhancement

#223 v2.1.4
  app/admin/about/page.tsx
  package.json
Labels: :memo:documentation

#225 refactor: Update type definitions and imports for improved type safety
  app/admin/page.tsx
  components/admin/dashboard/CardList.tsx
  components/admin/list/ImageBatchDeleteSheet.tsx
  components/admin/list/ImageView.tsx
  components/admin/list/ListProps.tsx
  components/album/ExifView.tsx
  components/album/MasonryItem.tsx
  components/layout/AlbumDrawer.tsx
  components/layout/DynamicNavbar.tsx
  components/layout/Header.tsx
  components/layout/HeaderLink.tsx
  types/index.ts
Labels: :recycle:refactor

#229 doc: update readme
  README.md
  picimpact.jpg
Labels: :memo:documentation
