Repository besscroft/PicImpact, pull requests merged in 2025-05, with the labels that each got.

#284 Chore/memo
  README.md
  app/admin/about/page.tsx
  app/layout.tsx
  eslint.config.mjs
  netlify.toml
Labels: :bug:bug

#289 style: fix list options mobile style
  components/admin/list/list-props.tsx
  components/icons/circle-chevron-down.tsx
Labels: :bug:bug

#291 feat: enhance file upload functionality with S3 and R2 support
  components/admin/upload/simple-file-upload.tsx
  hono/file.ts
  hono/images.ts
  hono/settings.ts
  instrumentation.ts
  lib/utils/file.ts
  package.json
  pnpm-lock.yaml
  server/db/operate/configs.ts
  server/lib/r2.ts
  server/lib/s3.ts
Labels: :sparkles:enhancement

#292 fix: direct upload not working
  hono/file.ts
  hono/images.ts
  lib/utils/file.ts
Labels: :bug:bug

#293 feat: enhance download functionality for S3 and R2
  components/album/gallery-image.tsx
  components/album/preview-image.tsx
  hono/download.ts
  hono/index.ts
  hono/settings.ts
  instrumentation.ts
  server/db/operate/configs.ts
  server/lib/r2.ts
  server/lib/s3.ts
Labels: :sparkles:enhancement

#296 refactor: 调整代码以消除Docker和Next.js构建阶段的部分警告
  Dockerfile
  app/layout.tsx
Labels: :recycle:refactor
